#!/bin/bash
set -euo pipefail

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[0;33m'
BLUE='\033[0;34m'
NC='\033[0m'

# Configuration
AWS_REGION="${AWS_REGION:-us-east-1}"
PROJECT_NAME="poc-eks-aws"
BUCKET_NAME="${PROJECT_NAME}-tfstate-$(aws sts get-caller-identity --query Account --output text 2>/dev/null || echo 'unknown')"
DYNAMODB_TABLE="${PROJECT_NAME}-tflock"

echo -e "${BLUE}═══════════════════════════════════════════════════════════════${NC}"
echo -e "${BLUE}  Terraform State Backend Bootstrap${NC}"
echo -e "${BLUE}═══════════════════════════════════════════════════════════════${NC}"
echo ""
echo -e "${BLUE}Configuration:${NC}"
echo "  AWS Region:      ${AWS_REGION}"
echo "  S3 Bucket:       ${BUCKET_NAME}"
echo "  DynamoDB Table:  ${DYNAMODB_TABLE}"
echo ""

# ─────────────────────────────────────────────────────────────────
# Validate AWS Credentials
# ─────────────────────────────────────────────────────────────────
echo -e "${YELLOW}▶ Validating AWS credentials...${NC}"

if ! aws sts get-caller-identity &>/dev/null; then
    echo -e "${RED}✗ AWS credentials not configured${NC}"
    echo "  Please configure AWS credentials or set AWS_PROFILE"
    exit 1
fi

ACCOUNT_ID=$(aws sts get-caller-identity --query Account --output text)
echo -e "${GREEN}✓ Authenticated as account: ${ACCOUNT_ID}${NC}"
echo ""

# Update bucket name with actual account ID
BUCKET_NAME="${PROJECT_NAME}-tfstate-${ACCOUNT_ID}"

# ─────────────────────────────────────────────────────────────────
# Create S3 Bucket
# ─────────────────────────────────────────────────────────────────
echo -e "${YELLOW}▶ Creating S3 bucket for Terraform state...${NC}"

if aws s3api head-bucket --bucket "${BUCKET_NAME}" 2>/dev/null; then
    echo -e "${GREEN}✓ Bucket '${BUCKET_NAME}' already exists${NC}"
else
    # Create bucket (us-east-1 doesn't need LocationConstraint)
    if [ "${AWS_REGION}" = "us-east-1" ]; then
        aws s3api create-bucket \
            --bucket "${BUCKET_NAME}" \
            --region "${AWS_REGION}"
    else
        aws s3api create-bucket \
            --bucket "${BUCKET_NAME}" \
            --region "${AWS_REGION}" \
            --create-bucket-configuration LocationConstraint="${AWS_REGION}"
    fi
    echo -e "${GREEN}✓ Bucket '${BUCKET_NAME}' created${NC}"
fi

# Enable versioning
echo -e "${YELLOW}  Enabling versioning...${NC}"
aws s3api put-bucket-versioning \
    --bucket "${BUCKET_NAME}" \
    --versioning-configuration Status=Enabled
echo -e "${GREEN}✓ Versioning enabled${NC}"

# Enable encryption
echo -e "${YELLOW}  Enabling encryption...${NC}"
aws s3api put-bucket-encryption \
    --bucket "${BUCKET_NAME}" \
    --server-side-encryption-configuration '{
        "Rules": [
            {
                "ApplyServerSideEncryptionByDefault": {
                    "SSEAlgorithm": "AES256"
                }
            }
        ]
    }'
echo -e "${GREEN}✓ Encryption enabled${NC}"

# Block public access
echo -e "${YELLOW}  Blocking public access...${NC}"
aws s3api put-public-access-block \
    --bucket "${BUCKET_NAME}" \
    --public-access-block-configuration '{
        "BlockPublicAcls": true,
        "IgnorePublicAcls": true,
        "BlockPublicPolicy": true,
        "RestrictPublicBuckets": true
    }'
echo -e "${GREEN}✓ Public access blocked${NC}"

echo ""

# ─────────────────────────────────────────────────────────────────
# Create DynamoDB Table
# ─────────────────────────────────────────────────────────────────
echo -e "${YELLOW}▶ Creating DynamoDB table for state locking...${NC}"

if aws dynamodb describe-table --table-name "${DYNAMODB_TABLE}" --region "${AWS_REGION}" &>/dev/null; then
    echo -e "${GREEN}✓ Table '${DYNAMODB_TABLE}' already exists${NC}"
else
    aws dynamodb create-table \
        --table-name "${DYNAMODB_TABLE}" \
        --attribute-definitions AttributeName=LockID,AttributeType=S \
        --key-schema AttributeName=LockID,KeyType=HASH \
        --billing-mode PAY_PER_REQUEST \
        --region "${AWS_REGION}"
    
    echo -e "${YELLOW}  Waiting for table to be active...${NC}"
    aws dynamodb wait table-exists --table-name "${DYNAMODB_TABLE}" --region "${AWS_REGION}"
    echo -e "${GREEN}✓ Table '${DYNAMODB_TABLE}' created${NC}"
fi

echo ""

# ─────────────────────────────────────────────────────────────────
# Generate Backend Configuration
# ─────────────────────────────────────────────────────────────────
echo -e "${YELLOW}▶ Generating backend configuration...${NC}"

cat > infra/state/backend.conf << EOF
# Terraform Backend Configuration
# Generated by aws-init.sh on $(date)
#
# Usage:
#   cd infra/environments/dev
#   terraform init -backend-config=../../state/backend.conf
#
# Each environment defines its own 'key' in backend.tf:
#   - dev:  dev/terraform.tfstate
#   - prod: prod/terraform.tfstate

bucket         = "${BUCKET_NAME}"
region         = "${AWS_REGION}"
dynamodb_table = "${DYNAMODB_TABLE}"
encrypt        = true
EOF

echo -e "${GREEN}✓ Backend config written to infra/state/backend.conf${NC}"

echo ""

# ─────────────────────────────────────────────────────────────────
# Summary
# ─────────────────────────────────────────────────────────────────
echo -e "${BLUE}═══════════════════════════════════════════════════════════════${NC}"
echo -e "${GREEN}  Terraform backend initialized!${NC}"
echo -e "${BLUE}═══════════════════════════════════════════════════════════════${NC}"
echo ""
echo -e "${BLUE}Resources Created:${NC}"
echo "  S3 Bucket:       ${BUCKET_NAME}"
echo "  DynamoDB Table:  ${DYNAMODB_TABLE}"
echo "  Config File:     infra/state/backend.conf"
echo ""
echo -e "${BLUE}Next Steps:${NC}"
echo "  1. Review infra/state/backend.conf"
echo "  2. Run: make aws-plan"
echo "  3. Run: make aws-apply"
echo ""
